version: '3.8'

services:
  mahoot-feed:
    build: .
    container_name: mahoot-feed-generator
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mahoot-network

  # Optional: Add Redis for caching (for future scaling)
  # redis:
  #   image: redis:7-alpine
  #   container_name: mahoot-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped
  #   networks:
  #     - mahoot-network

networks:
  mahoot-network:
    driver: bridge

volumes:
  # redis-data:
